### ISSUE TITLE
reduce default concurrency to something more reasonable

### ISSUE THREAD

**Issue by soapiestwaffles** [soapiestwaffles/s3-nuke#3]
after testing s3-nuke on a large bucket, I was able to get up to ~8000 objects/sec when I burnt out the AWS rate limit. I figure something more reasonable like `5` concurrency

**Comment by soapiestwaffles** [comment]
will have to fix #5 first before I can figure out a reasonable amount of concurrency

**Comment by soapiestwaffles** [comment]
now that #7 is merged, going to run some tests on this

**Comment by mikelorant** [comment]
Recommend dropping this from `100` to `5`. Anything else is going to cause the rate limiter to kick in very quickly.

**Comment by soapiestwaffles** [comment]
agree!
